test:
  services:
    - image:codepeer

  script:
    - cd tictactoe
    - gnatsas
        analyze
        --inspector
        -P gnatsas.gpr
    - gnatsas
        report
        -P gnatsas.gpr
    - gnatsas
        report
        csv
        -P gnatsas.gpr
        --out $CI_PROJECT_DIR/tictactoe/gnatsas.csv
    - gnatsas
        report
        code-climate
        -P gnatsas.gpr
        --out $CI_PROJECT_DIR/tictactoe/code_quality_report.json
        --root $CI_PROJECT_DIR
    - zip -r $CI_PROJECT_DIR/gnatsas_analysis.zip gnatsas/
    - upload_generic_package eng/codepeer/gitlab-workflow $CI_PROJECT_DIR/gnatsas_analysis.zip $(echo "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA" | tr '/' '_')

  artifacts:
    when: always
    paths:
      - tictactoe/code_quality_report.json
      - tictactoe/gnatsas/
    reports:
      codequality: tictactoe/code_quality_report.json
