test:
  services:
    - image:codepeer

  script:
    - . ~/.aws_container_credentials
    - cd tictactoe
    - codepeer
        -P codepeer.gpr
        --level 4
    - codepeer
        -P codepeer.gpr
        --no-analysis
        --text
    - codepeer
        -P codepeer.gpr
        --no-analysis
        --csv --out $CI_PROJECT_DIR/tictactoe/codepeer.csv
    - codepeer
        -P codepeer.gpr
        --no-analysis
        --codeclimate --out $CI_PROJECT_DIR/tictactoe/code_quality_report.json
        --codeclimate-root $CI_PROJECT_DIR
    - zip -r $CI_PROJECT_DIR/codepeer_analysis.zip codepeer/
    - upload_generic_package eng/codepeer/gitlab-workflow $CI_PROJECT_DIR/codepeer_analysis.zip "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"

  artifacts:
    when: always
    paths:
      - tictactoe/code_quality_report.json
      - tictactoe/codepeer/
    reports:
      codequality: tictactoe/code_quality_report.json
