test:
  services:
    - image:codepeer

  script:
    - codepeer
        -P tictactoe/codepeer.gpr
        --level 4
        --text
    - codepeer
        -P tictactoe/codepeer.gpr
        --no-analysis
        --csv --out $CI_PROJECT_DIR/tictactoe/codepeer.csv
    - codepeer_csv_to_code_climate_json
        -P tictactoe/codepeer.gpr
        --input $CI_PROJECT_DIR/tictactoe/codepeer.csv
        --output $CI_PROJECT_DIR/tictactoe/code_quality_report.json
        --base_path $CI_PROJECT_DIR

  artifacts:
    when: always
    paths:
      - tictactoe/code_quality_report.json
      - tictactoe/codepeer/codepeer.cpms
    reports:
      codequality: tictactoe/code_quality_report.json

