test:
  services:
    - image:codepeer

  script:
    - cd tictactoe
    - gnatsas
        analyze
        --inspector
        -P gnatsas.gpr
    - gnatsas
        report
        -P gnatsas.gpr
    - gnatsas
        report
        code-climate
        -P gnatsas.gpr
        --out $CI_PROJECT_DIR/tictactoe/code_quality_report.json
        --root $CI_PROJECT_DIR
    - zip -r $CI_PROJECT_DIR/gnatsas_analysis.zip gnatsas/
    # using SLUG which avoids forbidden characters within the version number
    # see e.g. https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/regex/packages.rb#L250 
    # for the generic package version regex
    - upload_generic_package eng/codepeer/gitlab-workflow $CI_PROJECT_DIR/gnatsas_analysis.zip "$CI_COMMIT_REF_SLUG"

  artifacts:
    when: always
    paths:
      - tictactoe/code_quality_report.json
      - tictactoe/gnatsas/
    reports:
      codequality: tictactoe/code_quality_report.json
stages:
  - test

autolint:
  services:
    - image:lint

  script:
    - autolint --check --output-code-climate-report=code_quality_report.json .

  allow_failure: true

  artifacts:
    when: always
    reports:
      codequality: code_quality_report.json
