test:
  services:
    - image:codepeer

  script:
    - . ~/.aws_container_credentials
    - cd tictactoe
    - gnatsas
        analyze
        -P codepeer.gpr
    - gnatsas
        report
        -P codepeer.gpr
    - gnatsas
        report
        csv
        -P codepeer.gpr
        --out $CI_PROJECT_DIR/tictactoe/codepeer.csv
    - gnatsas
        report
        code-climate
        -P codepeer.gpr
        --out $CI_PROJECT_DIR/tictactoe/code_quality_report.json
        --root $CI_PROJECT_DIR
    - zip -r $CI_PROJECT_DIR/codepeer_analysis.zip codepeer/
    - upload_generic_package eng/codepeer/gitlab-workflow $CI_PROJECT_DIR/codepeer_analysis.zip "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"

  artifacts:
    when: always
    paths:
      - tictactoe/code_quality_report.json
      - tictactoe/gnatsas/
    reports:
      codequality: tictactoe/code_quality_report.json
