test:
  services:
    - image:pe-base

  before_script:
    - anod init wave
    - cd wave
    - anod install --latest gnatsas
    - eval $(anod printenv gnatsas)
    - cd ..

  script:
    - cd tictactoe
    - gnatsas
        analyze
        -P gnatsas.gpr
    - gnatsas
        report
        -P gnatsas.gpr
    - gnatsas
        report
        code-climate
        -P gnatsas.gpr
        --out $CI_PROJECT_DIR/tictactoe/code_quality_report.json
        --root $CI_PROJECT_DIR
    - zip $CI_PROJECT_DIR/gnatsas_analysis.zip --recurse-pattern "gnatsas/*/*.sar"
    - zip $CI_PROJECT_DIR/gnatsas_analysis.zip --recurse-pattern "gnatsas/*/*.sam"
    - zip $CI_PROJECT_DIR/gnatsas_analysis.zip --recurse-pattern "gnatsas/*/*runs_info.json"
    # using commit SLUG which avoids forbidden characters within the version number
    # see e.g. https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/regex/packages.rb#L250 
    # for the generic package version regex
    - upload_generic_package "$CI_PROJECT_PATH" "$CI_PROJECT_DIR/gnatsas_analysis.zip" "$CI_COMMIT_REF_SLUG"

  artifacts:
    when: always
    paths:
      - tictactoe/code_quality_report.json
      - tictactoe/gnatsas/*/*.sar
      - tictactoe/gnatsas/*/*.sam
      - tictactoe/gnatsas/*/*runs_info.json
    reports:
      codequality: tictactoe/code_quality_report.json
stages:
  - test

autolint:
  services:
    - image:lint

  script:
    - autolint --check --output-code-climate-report=code_quality_report.json .

  allow_failure: true

  artifacts:
    when: always
    reports:
      codequality: code_quality_report.json
